### ISSUE TITLE
Running deployment from package causes ->  Unable to list hosted zones in Route53

### ISSUE THREAD

**Issue by ashley-hurkoo** [artoliukkonen/serverless-appsync-cloudfront#5]
I have just found quite a unusual one. Running deployment from a package causes the plugin to fail.

Replication step:

```
SLS_DEBUG=* serverless package --stage dev --package sls-package-output
SLS_DEBUG=* serverless deploy -v --stage dev --package sls-package-output
```

Error:

```
Error --------------------------------------------------

  Error: Error: Unable to list hosted zones in Route53.
  TypeError: Cannot read property 'listHostedZones' of undefined
      at ServerlessAppSyncCloudFrontPlugin.getRoute53HostedZoneId (/Users/ashleyhurkoo/workspace/hotel-service/node_modules/serverless-appsync-cloudfront/index.js:251:13)
      at ServerlessAppSyncCloudFrontPlugin.changeResourceRecordSet (/Users/ashleyhurkoo/workspace/hotel-service/node_modules/serverless-appsync-cloudfront/index.js:153:44)
```

Deploying directly using the following works:

```
SLS_DEBUG=* serverless deploy -v --stage dev
```

**Comment by vlutsyuk-amplify** [comment]
faced with the same issue, any ideas why that might happen

**Comment by mikiboy** [comment]
same issue.. :(
